//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_order_items
    {
        public int list_of_order_items__id { get; set; }
        public int item_product_id { get; set; }
        public int item_count { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
