//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orders_id { get; set; }
        public System.DateTime date { get; set; }
        public string name_client { get; set; }
        public int list_of_order_items { get; set; }
    }
}
